Hamza/tip contact us
CERP/edmarkaz pull request #100
Opened 2021-11-10 10:42 UTC by hmzahmed

- Create secure endpoint for submitting contact requests
- Create new table schema for tip contact requests
- Save information to our db
- Send slack message on each contact request

2021-11-10 10:59 UTC, mudssrali requested changes
Thanks @hmzahmed that's awesome first backend PR 🎉 - a few comments

2021-11-10 10:59 UTC, mudssrali commented on elixir/lib/sarkar/server/mis.ex
> +		[ auth_token ] = get_req_header(conn, "auth-token")
spacing

2021-11-10 10:59 UTC, mudssrali commented on elixir/lib/sarkar/server/mis.ex
> +		if String.length(client_id)>0 and String.length(auth_token)>0 do
I would say there would be two check here:
- is_binary (client-id)
- length (length of both client_id and auth_token is known to us)

2021-11-10 10:59 UTC, mudssrali commented on elixir/lib/sarkar/server/mis.ex
> +					EdMarkaz.Slack.send_alert("Received a Contact Request from #{request_data["request_person"]}", "#tip-contact-requests")
Create a complete request as a slack notification payload

2021-11-10 10:59 UTC, mudssrali commented on elixir/lib/sarkar/server/mis.ex
> +				|> send_resp(401, "client-id not submitted")
It's always good practice to return json, e.g. something like
```elixir
%{ status: 401, message: "Client id is invalid"}
```

2021-11-10 10:59 UTC, mudssrali commented on elixir/lib/sarkar/targeted_instructions/targeted_instructions.ex
> +	def submit_contact_data(client_id,auth_token,contact_data) do
A few things here:
- spacing
- save_contact_request

2021-11-10 10:59 UTC, mudssrali commented on elixir/lib/sarkar/targeted_instructions/targeted_instructions.ex
> +			{:ok, %Postgrex.Result{num_rows: 0}} -> {:error, "Failed to Authorize", 401} # This happens when we cant find the client id in our db
- comment before the code line
- `cant` -> cannot

2021-11-10 10:59 UTC, mudssrali commented on elixir/lib/sarkar/targeted_instructions/targeted_instructions.ex
> +				{:error, "An Unknown error has occured",500}
- comments before each of code snippet not infront of
- spacing

2021-11-10 16:15 UTC, hmzahmed commented
Read the comments, will implement them first thing tomorrow

2021-11-11 09:21 UTC, hmzahmed commented on elixir/lib/sarkar/server/mis.ex
> +					EdMarkaz.Slack.send_alert("Received a Contact Request from #{request_data["request_person"]}", "#tip-contact-requests")
I dont understand what this means

2021-11-20 07:49 UTC, merged