Chore: TIP - Analytics Report Generator
CERP/edmarkaz pull request #109
Opened 2022-03-29 22:00 UTC by ZarishIqbal

### This PR contains the following:

- [x] Script to generate and upload teachers' activity analytics
- [x] Script to generate and upload TIP baseline schools' analytics

2022-04-04 11:54 UTC, mudssrali requested changes
Just a few changes. Thanks @ZarishIqbal  - Also can you please documentation for newly added analytics CSV generation logic. This would help new developers to understand the logic easily.

2022-04-04 11:54 UTC, mudssrali commented on elixir/lib/sarkar/targeted_instructions/faculty.ex
> +          |> Enum.flat_map(fn x -> x end)
why we're doing flat map twice? We could use reduce to flat the list
```
Enum.reduce([], fn list, agg -> .... end)
```

2022-04-04 11:54 UTC, mudssrali commented on elixir/lib/sarkar/targeted_instructions/faculty.ex
> +      |> Enum.flat_map(fn x -> x end)
again here

2022-04-04 11:54 UTC, mudssrali commented on elixir/lib/sarkar/targeted_instructions/faculty.ex
> +            IO.puts("#{index + 1} : #{school_id} alread started")
we don't need to have these log messages - these are a lot and repeatedly.

2022-04-04 11:54 UTC, mudssrali commented on elixir/lib/sarkar/targeted_instructions/faculty.ex
> +
we have this duplicate logic - can we move them to a reusable place?

2022-04-04 11:54 UTC, mudssrali commented on elixir/lib/sarkar/targeted_instructions/grade_report_generator.ex
> +        IO.puts(object.mediaLink)
We can run them in task to achieve concurrency and optimization as
```ex
Task.start_link(fn ->
    grades_csv = TargetedInstructions.Schools.get_grades_report()
    case Google.upload_csv("TIP_BASELINE_SCHOOLS_REPORT", grades_csv) do
      {:ok, _object} ->
        IO.puts(object.mediaLink)
      _ ->
        "Not Uploaded O_o"
    end
end)
```

Same goes for other tasks.

2022-04-04 13:53 UTC, ZarishIqbal commented
@mudssrali I have made the changes.

2022-04-04 18:20 UTC, mudssrali commented on elixir/lib/sarkar/targeted_instructions/faculty.ex
> +      ~w(trainingactivity_wk1 trainingactivity_wk2 trainingactivity_wk4 techactivity_wk1 techactivity_wk2 techactivity_wk3 techactivity_wk4 techactivity_wk6 techactivity_wk7 techactivity_wk8)
is that correct, `trainingactivity_wk1 trainingactivity_wk2 trainingactivity_wk4` ? we don't have training activity_wk3? @ZarishIqbal

2022-04-05 00:41 UTC, ZarishIqbal commented on elixir/lib/sarkar/targeted_instructions/faculty.ex
> +      ~w(trainingactivity_wk1 trainingactivity_wk2 trainingactivity_wk4 techactivity_wk1 techactivity_wk2 techactivity_wk3 techactivity_wk4 techactivity_wk6 techactivity_wk7 techactivity_wk8)
If you check the csv, variable 3 is for youtube views which we left out purposely.

2022-04-05 00:46 UTC, mudssrali commented on elixir/lib/sarkar/targeted_instructions/faculty.ex
> +      ~w(trainingactivity_wk1 trainingactivity_wk2 trainingactivity_wk4 techactivity_wk1 techactivity_wk2 techactivity_wk3 techactivity_wk4 techactivity_wk6 techactivity_wk7 techactivity_wk8)
Thanks @ZarishIqbal

2022-04-05 01:12 UTC, merged