Feature/integrate telenor api
CERP/edmarkaz pull request #65
Opened 2020-09-29 20:52 UTC by HumnaAleem

2020-09-30 22:05 UTC, taimur38 reviewed
Few things to check. I think code can be cleaned up on sending the message, and have some questions about the ets table

2020-09-30 22:05 UTC, taimur38 commented on elixir/lib/sarkar/telenor/telenor.ex
> +						case get("sendsms.jsp", query: [session_id: session_id, to: number, text: text, mask: System.get_env("TELENOR_MASK")]) do
This should be made it's own function we call it here 3 times

2020-09-30 22:05 UTC, taimur38 commented on elixir/lib/sarkar/telenor/telenor.ex
> +				[{_, session_id, timestamp}] = session_obj
I assume this could return an array with more than just one item in it

2020-09-30 22:05 UTC, taimur38 commented on elixir/lib/sarkar/application.ex
> +		:ets.new(:telenor_ets, [:set, :public, :named_table])
Does the :set atom here prevent duplicate keys?

2020-10-01 06:40 UTC, HumnaAleem commented on elixir/lib/sarkar/ets_store/store.ex
> +defmodule EdMarkaz.EtsStore do
ok

2020-10-01 06:48 UTC, HumnaAleem commented on elixir/lib/sarkar/ets_store/store.ex
> +		:ets.insert_new(:telenor_ets, data)
There are two functions `insert` and `insert_new`. insert function replaces previous data if the key is the same. but insert new return false if data exists with the same key. I guess we should use `insert`.

2020-10-01 06:49 UTC, HumnaAleem commented on elixir/lib/sarkar/telenor/telenor.ex
> +					case get("sendsms.jsp", query: [session_id: res, to: number, text: text, mask: System.get_env("TELENOR_MASK")]) do
Yes, it is default mask.

2020-10-01 06:49 UTC, HumnaAleem commented on elixir/lib/sarkar/telenor/telenor.ex
> +						case get("sendsms.jsp", query: [session_id: session_id, to: number, text: text, mask: System.get_env("TELENOR_MASK")]) do
sure definitly

2020-10-01 07:01 UTC, HumnaAleem commented on elixir/lib/sarkar/application.ex
> +		:ets.new(:telenor_ets, [:set, :public, :named_table])
No, it's just a type of ets table.
`This is the default table type. One value per key. The keys are unique`

2020-10-01 07:06 UTC, HumnaAleem commented on elixir/lib/sarkar/telenor/telenor.ex
> +				[{_, session_id, timestamp}] = session_obj
done

2020-10-01 07:06 UTC, HumnaAleem commented on elixir/lib/sarkar/telenor/telenor.ex
> +							IO.puts "SEND SMS ERROR to #{number}"
done

2020-10-01 10:00 UTC, taimur38 commented on elixir/lib/sarkar/ets_store/store.ex
> +		:ets.insert_new(:telenor_ets, data)
yes makes sense. and it doesn't error if it's the first time we are inserting right

2020-10-01 10:01 UTC, taimur38 commented on elixir/lib/sarkar/telenor/telenor.ex
> +					case get("sendsms.jsp", query: [session_id: res, to: number, text: text, mask: System.get_env("TELENOR_MASK")]) do
my point is we don't need to have an environment variable for the mask here, shouldn't need to pass it as a parameter

2020-10-01 10:06 UTC, taimur38 requested changes

2020-10-01 10:06 UTC, taimur38 commented on elixir/lib/sarkar/telenor/telenor.ex
> +	def send(session_id, number, text) do
I think this overrides the built in `send` function in elixir -- can we make this a private method (defp) and call it send_sms as an overload on the previous method. Since it takes 3 arguments, it will not clash with the above send_sms method

2020-10-01 10:06 UTC, taimur38 commented on elixir/lib/sarkar/telenor/telenor.ex
> +		case get("sendsms.jsp", query: [session_id: session_id, to: number, text: text, mask: System.get_env("TELENOR_MASK")]) do
can we remove the mask argument in the request here - I think we don't need it.

2020-10-01 10:06 UTC, taimur38 commented on elixir/lib/sarkar/telenor/telenor.ex
> +				{_, session_id, timestamp} = head
[{_, session_id, timestamp} | _] = session_obj

2020-10-01 10:08 UTC, HumnaAleem commented on elixir/lib/sarkar/telenor/telenor.ex
> +					case get("sendsms.jsp", query: [session_id: res, to: number, text: text, mask: System.get_env("TELENOR_MASK")]) do
ok

2020-10-01 10:14 UTC, HumnaAleem commented on elixir/lib/sarkar/ets_store/store.ex
> +		:ets.insert_new(:telenor_ets, data)
yes

2020-10-01 10:22 UTC, HumnaAleem commented on elixir/lib/sarkar/telenor/telenor.ex
> +		case get("sendsms.jsp", query: [session_id: session_id, to: number, text: text, mask: System.get_env("TELENOR_MASK")]) do
Without a mask it gives error 103.

2020-10-01 10:23 UTC, HumnaAleem commented on elixir/lib/sarkar/telenor/telenor.ex
> +	def send(session_id, number, text) do
done

2020-10-01 10:23 UTC, HumnaAleem commented on elixir/lib/sarkar/telenor/telenor.ex
> +				{_, session_id, timestamp} = head
done

2020-10-01 22:33 UTC, taimur38 requested changes
Almost set - we will need to add environment variables to the deployment tomorrow

2020-10-01 22:33 UTC, taimur38 commented on elixir/lib/sarkar/telenor/telenor.ex
> +				case get_session_id() do
Can we also make this segment it's own function? A method called `refresh_and_send`. I think then this function will look really clean.

2020-10-01 22:33 UTC, taimur38 commented on elixir/lib/sarkar/telenor/telenor.ex
> +		case get("sendsms.jsp", query: [session_id: session_id, to: number, text: text, mask: "ILMEXCHANGE"]) do
The documentation says that if we don't supply the mask variable, then it will use the default mask set in the portal. That's why I'm saying to not supply thee variable here.

2020-10-02 10:14 UTC, HumnaAleem commented on elixir/lib/sarkar/telenor/telenor.ex
> +				case get_session_id() do
done

2020-10-02 10:14 UTC, HumnaAleem commented on elixir/lib/sarkar/telenor/telenor.ex
> +		case get("sendsms.jsp", query: [session_id: session_id, to: number, text: text, mask: "ILMEXCHANGE"]) do
Yes, I read the same thing But I tried without mask it doesn't work.

2020-10-02 10:48 UTC, taimur38 commented on elixir/lib/sarkar/telenor/telenor.ex
> +		case get("sendsms.jsp", query: [session_id: session_id, to: number, text: text, mask: "ILMEXCHANGE"]) do
ok sounds good

2020-10-02 10:50 UTC, taimur38 approved these changes
Looks good!

2020-10-02 10:51 UTC, taimur38 commented
just wait til our call today to merge this in -- we need to set environment variables in our deployment configuration before we can merge

2020-10-02 13:23 UTC, merged