Targeted instruction
CERP/edmarkaz pull request #74
Opened 2020-11-14 09:44 UTC by HumnaAleem

2020-11-24 11:38 UTC, taimur38 requested changes
comments left on slack

2020-11-24 11:38 UTC, taimur38 commented on elixir/lib/sarkar/student_portal/student_portal.ex
> +
why is this function in student_portal.ex?

2020-12-04 12:51 UTC, taimur38 requested changes

2020-12-04 12:51 UTC, taimur38 commented on elixir/lib/mix/tasks/platform.ex
> +	def run(["ingest_diagnostic_result", school_id, diagnostic_result]) do
what was the intention of this task again?

2020-12-04 12:51 UTC, taimur38 commented on elixir/lib/sarkar/action_handlers/mis.ex
> +		response = Map.merge(assessments, curriculum)
don't we want to create a response that does:
```elixir
%{
   "assessments" => assessments,
   "curriculum" => curriculum 
}
```

2020-12-04 12:51 UTC, taimur38 commented on elixir/lib/sarkar/targeted_instructions/targeted_instructions.ex
> +				[head | tail ] = curriculum
isn't curriculum an object?

2020-12-04 12:51 UTC, taimur38 commented on elixir/lib/sarkar/targeted_instructions/targeted_instructions.ex
> +			curriculum
you supply 2 variable placeholders ($1 and $2) but only give `curriculum` to be swapped in...

2020-12-04 12:51 UTC, taimur38 commented on elixir/lib/sarkar/targeted_instructions/targeted_instructions.ex
> +	def insert_targeted_instruction_curriculum(curriculum) do
what is curriculum here? I think that will anser the next few questions

2020-12-04 12:51 UTC, taimur38 commented on elixir/lib/sarkar/targeted_instructions/targeted_instructions.ex
> +	def insert_targeted_instruction_assessments(assessments) do
same questions here as for curriculum...

2020-12-04 12:51 UTC, taimur38 commented on elixir/lib/sarkar/targeted_instructions/targeted_instructions.ex
> +		end
This should return a map of `{ assessment_id: assessment }` not just an array of assessments

2020-12-04 12:51 UTC, taimur38 commented on elixir/lib/sarkar/targeted_instructions/targeted_instructions.ex
> +
same point here as for assessments

2020-12-06 17:55 UTC, HumnaAleem commented on elixir/lib/sarkar/targeted_instructions/targeted_instructions.ex
> +	def insert_targeted_instruction_curriculum(curriculum) do
id + curriculum obj

2020-12-06 17:55 UTC, HumnaAleem commented on elixir/lib/sarkar/targeted_instructions/targeted_instructions.ex
> +	def insert_targeted_instruction_assessments(assessments) do
same

2020-12-06 17:55 UTC, HumnaAleem commented on elixir/lib/mix/tasks/platform.ex
> +	def run(["ingest_diagnostic_result", school_id, diagnostic_result]) do
I didn't get your point.

2020-12-07 12:22 UTC, taimur38 commented on elixir/lib/mix/tasks/platform.ex
> +	def run(["ingest_diagnostic_result", school_id, diagnostic_result]) do
ingest_diagnostic_exams

2020-12-07 12:26 UTC, taimur38 commented on elixir/lib/mix/tasks/platform.ex
> +				"slo" => slo
this should be an array

2020-12-07 12:27 UTC, taimur38 commented on elixir/lib/mix/tasks/platform.ex
> +				"slo" => slo
"slo" => [slo]

2020-12-07 12:39 UTC, taimur38 commented on elixir/lib/sarkar/action_handlers/mis.ex
> +		response = Map.merge(assessments, curriculum)
%{ "tests", "slo_mapping", "curriculum" }

2020-12-09 06:37 UTC, HumnaTesmem commented on elixir/lib/mix/tasks/platform.ex
> +				"slo" => slo
I know there can be more than one slo I handled it on frontend. But If u say I can make it an array here.

2020-12-10 09:51 UTC, taimur38 requested changes

2020-12-10 09:51 UTC, taimur38 commented on elixir/lib/sarkar/action_handlers/mis.ex
> +		}
use strings instead of atoms here; "tests" => assessments etc

2020-12-10 09:51 UTC, taimur38 commented on elixir/lib/sarkar/targeted_instructions/targeted_instructions.ex
>  				[head | tail ] = curriculum
what is the "head" of curriculum here? now curriculum is an object

2020-12-10 09:51 UTC, taimur38 commented on elixir/lib/sarkar/targeted_instructions/targeted_instructions.ex
>  				[head | tail ] = assessments
assessment is now an object not an array. what is "head"

2020-12-10 09:51 UTC, taimur38 commented on elixir/lib/sarkar/targeted_instructions/targeted_instructions.ex
> +				[head | tail ] = slo_mapping
isn't slo_mapping an object?

2020-12-10 10:29 UTC, HumnaTesmem commented on elixir/lib/sarkar/targeted_instructions/targeted_instructions.ex
>  				[head | tail ] = curriculum
map is returning an array . We are getting first entry from array that is object

2020-12-10 10:30 UTC, taimur38 commented on elixir/lib/mix/tasks/platform.ex
> +				"slo" => slo
it should be an array on backend yeah

2020-12-10 10:38 UTC, HumnaTesmem commented on elixir/lib/mix/tasks/platform.ex
> +				"slo" => slo
ok

2020-12-10 11:23 UTC, taimur38 approved these changes

2020-12-10 11:24 UTC, merged